### PR TITLE
Pair programing accessibility

### PR DESCRIPTION
**Pull request by djo1975**
#### The basic structure of the page - no issues found

### CODE REVIEW

**Review by mckent05 — COMMENTED** [review]
Hi @djo1975, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have at least one commit from your coding partner, please note that this is a pair-programming milestone and it is required that all partners have at least one commit for this repo 👍 👍 

- Also, please note that you are to include a report on the changes you have made to improve the accessibility of your site 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by OyePriscilla — CHANGES_REQUESTED** [review]
Hi @djo1975 and @Reggeditt 😃, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

so-close-so-close-seth-meyers

## Highlights
Github flow observed✔️
Linters checks passed ✔️ 

## Required Changes ♻️

- [x] Please, according to the evaluation guidelines, we need to run your live demo through [this tool](https://www.aditus.io/button-contrast-checker/). Not all of the checks are passing for your project, kindly run your live demo through it and consider making all the changes suggested by the tool. ℹ️ 

- [x] I'm sorry to raise this, please I noticed that all the content of your web app are not aligned properly `@min-width: 768px`, this is not a good user experience. It's makes your beautiful app not easily accessible at a glance. Kindly take note to ensure that there is no horizontal overflow as well. Thanks. 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by djo1975** [comment]
I made changes in desktop.css to align @min-width: 768px. properly and I made all the necessary changes suggested by the Button Contrast Checker tool.

**Review by huseyinbiyik — APPROVED** [review]
Hi @djo1975,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Alt Text


## Highlights
- Required changes implemented well 👌

## Optional suggestions
- Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the sections exist in yours and placeholders are replaced with your project and personal data. Only optional section is FAQ.  Also please make sure you deleted the logo on the top unless you have your own personal logo. This is crucial to have a professional and instructive repository. 👌

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, "Add logo to navigation bar"

- Kindly add a software license and .gitignore file. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
